name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        片8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero 将所有错误视为警告。GitHub 编辑器的宽度为 127 个字符
        片8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - 名称：使用 pytest 进行测试
      运行： |
        conda安装pytest
        py测试
